(function(){
  const z=(zh,en)=>`<span data-zh="${zh.replaceAll('"','&quot;')}" data-en="${en.replaceAll('"','&quot;')}">${zh}</span>`;
  const page=(name,html)=>{const legacy=document.querySelector(`[data-page="legacy-${name}"]`);if(legacy){legacy.dataset.page=name;legacy.innerHTML=html;return legacy;}const el=document.createElement('section');el.className='page wrap';el.dataset.page=name;el.innerHTML=html;document.querySelector('[data-page="radar"]').before(el);return el};
  page('about',`
    <p class="section-kicker">About Ning</p><h2 class="section-title">Ning Huang / 黄宁</h2>
    <div class="about-grid"><div class="portrait-placeholder"><span>Postdoctoral Research Fellow</span><strong>Ning Huang, MD</strong><span>The University of Hong Kong</span></div><div class="about-copy">
      <p class="bio-lead">${z('Ning Huang（黄宁）现为香港大学博后研究员，获北京大学公共卫生学院医学博士学位，曾任新加坡南洋理工大学访问学者。她的研究横跨公共卫生、心理与行为科学、社会科学及数据科学，关注心理、行为、身体与发展健康，以及个体因素与家庭、学校、医疗服务、数字环境和社会结构之间的相互作用。她运用人群大数据、电子健康记录、数字健康与可解释人工智能，推动研究证据向干预、健康服务与社会政策转化。她也是国内VIPP-SD持证养育干预师之一，并具有心理咨询师专业资质。','Ning Huang, MD, is a Postdoctoral Research Fellow at the University of Hong Kong. She received her Doctor of Medicine degree from the School of Public Health at Peking University and was a Visiting Scholar at Nanyang Technological University, Singapore. Her interdisciplinary research spans public health, psychological and behavioural science, social science, and data science. She studies mental, behavioural, physical and developmental health, with particular attention to how individual factors interact with families, schools, health services, digital environments and social structures. Her work combines population-scale data, electronic health records, digital health and interpretable artificial intelligence to inform interventions, health services and social policy. She is also one of the certified VIPP-SD interveners in China and a qualified psychological counsellor.')}</p>
      <div class="credential-strip"><span>Population Health</span><span>Behavioural Science</span><span>AI & Digital Health</span><span>VIPP-SD</span></div>
      <a class="contact" href="mailto:huangning.pku@gmail.com">huangning.pku@gmail.com</a>
    </div></div>
    <section class="subsection"><h3 class="subsection-title">${z('学术经历','Academic Appointments & Education')}</h3><div class="timeline">
      <div class="timeline-item"><time>2025—</time><div><strong>${z('香港大学｜博后研究员','The University of Hong Kong | Postdoctoral Research Fellow')}</strong></div></div>
      <div class="timeline-item"><time>2021—2025</time><div><strong>${z('北京大学公共卫生学院｜医学博士','School of Public Health, Peking University | Doctor of Medicine')}</strong></div></div>
      <div class="timeline-item"><time>2023—2024</time><div><strong>${z('新加坡南洋理工大学｜访问学者','Nanyang Technological University, Singapore | Visiting Scholar')}</strong></div></div>
    </div></section>
    <section class="subsection"><h3 class="subsection-title">${z('荣誉与奖励','Honours & Awards')}</h3><div class="mini-grid"><div class="mini-card"><h4>2025</h4><p>${z('北京大学优秀毕业生','Outstanding Graduate, Peking University')}</p></div><div class="mini-card"><h4>2024</h4><p>${z('优秀医学生奖学金；北京大学三好学生','Outstanding Medical Student Scholarship; Outstanding Student, Peking University')}</p></div><div class="mini-card"><h4>2023</h4><p>${z('北京大学校长奖学金；北京大学三好学生','President Scholarship and Outstanding Student, Peking University')}</p></div><div class="mini-card"><h4>2022 / 2020</h4><p>${z('北京大学科研奖；华中科技大学优秀毕业生','Award for Scientific Research, Peking University; Outstanding Graduate, HUST')}</p></div></div></section>
    <section class="subsection"><h3 class="subsection-title">${z('学术服务与教学','Academic Service & Teaching')}</h3><div class="mini-grid"><div class="mini-card"><h4>${z('青年编委','Early-Career Editorial Boards')}</h4><p><em>PsyCh Journal</em>; <em>Health Psychology Research</em>; <em>Alpha Psychiatry</em></p></div><div class="mini-card"><h4>${z('同行评审','Peer Review')}</h4><p>BMC Medicine; Child Abuse & Neglect; BMC Public Health; BMC Psychiatry; Scientific Reports; BMC Pregnancy and Childbirth; Computers in Human Behavior Reports; Psychiatry Research Communications.</p></div><div class="mini-card"><h4>${z('教学与指导','Teaching & Mentoring')}</h4><p>${z('《社会医学》助教、公共卫生应急管理客座讲授，以及R、Python、Stata、SPSS和学术写作指导。','Teaching assistance in Social Medicine, guest teaching in Public Health Emergency Management, and mentoring in R, Python, Stata, SPSS and academic writing.')}</p></div></div></section>
  `);
  page('research',`
    <p class="section-kicker">Research Areas</p><h2 class="section-title">${z('研究方向','Research Areas')}</h2><p class="section-lead">${z('以全生命历程和多层次视角连接健康问题、数据方法与可转化行动。每一方向均由已发表研究与跨机构项目支撑。','A life-course and multilevel programme connecting health questions, data methods and actionable translation, grounded in published research and cross-institutional projects.')}</p>
    <div class="research-focus">
      <section class="focus-card"><span class="num">01</span><h3>${z('心理健康、逆境与全生命历程发展','Mental Health, Adversity & Life-course Development')}</h3><p>${z('研究心理福祉、焦虑与抑郁、创伤、欺凌、依恋、神经发展、睡眠与健康行为如何随生命历程相互作用。','Examining how well-being, anxiety and depression, trauma, bullying, attachment, neurodevelopment, sleep and health behaviours interact across the life course.')}</p><ul><li>${z('儿童、青少年、家庭与成人','Children, adolescents, families and adults')}</li><li>${z('队列、人群调查、系统综述与试验','Cohorts, population surveys, reviews and trials')}</li></ul></section>
      <section class="focus-card"><span class="num">02</span><h3>${z('多层次健康决定因素与健康公平','Multilevel Determinants of Health & Health Equity')}</h3><p>${z('从个体特征、认知、行为与能动性出发，研究其与家庭、学校、同伴、工作场所、社区、自然和数字环境、医疗系统以及社会经济、制度和政策条件的交互。','Studying individual characteristics, cognition, behaviour and agency in interaction with families, schools, peers, workplaces, communities, natural and digital environments, health systems, and socioeconomic, institutional and policy conditions.')}</p><ul><li>${z('风险、保护、韧性与不平等','Risk, protection, resilience and inequity')}</li><li>${z('多层模型、网络分析与政策评估','Multilevel models, network analysis and policy evaluation')}</li></ul></section>
      <section class="focus-card"><span class="num">03</span><h3>${z('数字健康、AI与人群干预科学','Digital Health, AI & Population Intervention Science')}</h3><p>${z('结合人群大数据、电子健康记录、数字表型与可解释机器学习，开发并评估可服务于个体、机构和政策的干预。','Combining population-scale data, electronic health records, digital phenotyping and interpretable machine learning to develop and evaluate interventions for individuals, services and policy.')}</p><ul><li>${z('可解释AI与动态风险评估','Interpretable AI and dynamic risk assessment')}</li><li>${z('数字干预、实施科学与健康服务','Digital intervention, implementation and health services')}</li></ul></section>
    </div><div class="quick"><a href="?view=projects">${z('查看研究项目 →','View projects →')}</a><a href="?view=publications">${z('查看论文成果 →','View publications →')}</a><a href="?view=contact">${z('讨论研究合作 →','Discuss collaboration →')}</a></div>
  `);
  const projectCard=(title,meta,intro,role)=>`<article class="project-card"><h4>${title}</h4><span class="project-meta">${meta}</span><p>${intro}</p><p class="contribution"><strong>${z('我的工作：','My contribution:')}</strong> ${role}</p></article>`;
  page('projects',`
    <p class="section-kicker">Research Projects</p><h2 class="section-title">${z('研究项目','Research Projects')}</h2><p class="section-lead">${z('项目名称、国家或地区、资助来源和合作导师按学术履历呈现；重点说明项目研究什么，以及Ning在其中承担的工作。','Projects are presented with their full titles, location, funder and principal investigator or collaborator, together with Ning’s contribution.')}</p>
    <section class="project-group"><h3>${z('当前项目','Current Projects')}</h3><div class="project-list">
      ${projectCard(z('儿童发展与电子健康记录关联研究','Linked Child Development and Electronic Health Record Research'),'Hong Kong · 2025— | The University of Hong Kong',z('连接儿童发展资料与临床电子健康记录，研究早期经历、发展轨迹和后续健康服务结局。','Linking child-development data with clinical electronic health records to examine early experience, developmental trajectories and later health-service outcomes.'),z('研究设计、变量框架、数据分析与论文工作。','Study design, variable framework, analysis and manuscript development.'))}
      ${projectCard(z('欺凌与心理健康的可解释机器学习研究','Explainable Machine Learning for Bullying and Mental Health'),'International · Current',z('利用可解释机器学习识别欺凌经历与心理健康风险的异质模式，并提高预测结果的可沟通性。','Using interpretable machine learning to identify heterogeneous patterns of bullying and mental-health risk and improve the communicability of predictions.'),z('研究构思、分析方案、模型解释与成果转化。','Conceptualisation, analysis plan, model interpretation and translation.'))}
      ${projectCard('FamonyAI', 'China / International · Prototype',z('面向家庭与养育支持的AI原型，探索如何把循证养育知识转化为可访问、可评估的人机协同支持。','An AI prototype for family and parenting support, translating evidence-based parenting knowledge into accessible, evaluable human–AI support.'),z('产品构思、证据框架、风险边界与原型评估。','Product concept, evidence framework, safety boundaries and prototype evaluation.'))}
    </div></section>
    <section class="project-group"><h3>${z('既往项目','Previous Projects')}</h3><div class="project-list">
      ${projectCard(z('儿童创伤后应激障碍预后与干预研究','Prognosis and Intervention for Post-traumatic Stress Disorder in Children'),'China | National Natural Science Foundation of China | PI: Jing Guo',z('围绕儿童创伤后应激反应的风险、保护因素、预后识别与干预路径开展研究。','Research on risk, protection, prognosis and intervention pathways for post-traumatic stress responses in children.'),z('参与研究设计、数据工作、分析与论文写作。','Study design, data work, analysis and manuscripts.'))}
      ${projectCard('LOVING Study','Singapore | Ministry of Health | Anne Rifkin-Graboi & team',z('通过纵向母婴与家庭研究理解早期关系、照护环境和儿童发展。','A longitudinal mother–infant and family study of early relationships, caregiving environments and child development.'),z('访问研究、数据分析与跨文化研究协作。','Visiting research, data analysis and cross-cultural collaboration.'))}
      ${projectCard('CARE Study','Singapore | Ministry of Education | Anne Rifkin-Graboi & team',z('关注儿童早期发展、照护关系与教育环境中的适应。','Examining early development, caregiving relationships and adaptation in educational contexts.'),z('数据分析、研究讨论与成果准备。','Data analysis, research development and output preparation.'))}
      ${projectCard('BE POSITIVE Study','Singapore | National Research Foundation | Anne Rifkin-Graboi & team',z('研究早期积极经验、家庭环境与儿童发展结果。','Investigating early positive experience, family environments and child developmental outcomes.'),z('跨团队研究协作、分析与学术交流。','Cross-team collaboration, analysis and academic exchange.'))}
      ${projectCard(z('主动健康视角下儿童青少年心理健康干预研究','Child and Adolescent Mental-health Intervention from an Active-health Perspective'),'China | Beijing Social Science Foundation | PI: Jing Guo',z('将主动健康理念与儿童青少年心理健康促进、学校和家庭支持相连接。','Connecting active-health approaches with child and adolescent mental-health promotion and school and family support.'),z('研究设计、问卷、数据分析与论文工作。','Study design, survey development, analysis and manuscripts.'))}
      ${projectCard(z('老年慢性病健康管理与服务路径研究','Health Management and Service Pathways for Older Adults with Chronic Conditions'),'China | PKU Institute for Global Health and Development | PI: Jing Guo',z('评估老年慢性病人群的健康管理需求、服务利用与可改善路径。','Assessing health-management needs, service use and actionable pathways for older adults with chronic conditions.'),z('文献、方案、数据分析与研究报告。','Evidence review, protocol, analysis and reporting.'))}
      ${projectCard(z('数字技术促进流感疫苗接种与健康经济学随机试验','Digital Technology, Influenza Vaccination and Health-economics Randomized Trial'),'China · 2024—2025 | Beijing Municipal Natural Science Foundation | PI: Jing Guo',z('以随机试验评估数字技术促进疫苗接种的效果、实施机制与健康经济学价值。','A randomized trial evaluating the effectiveness, implementation mechanisms and health-economic value of digital approaches to vaccination uptake.'),z('参与基金申请、方案优化、问卷和数据工作及随机试验研究。','Grant development, protocol refinement, survey and data work, and randomized-trial research.'))}
      ${projectCard(z('积极老龄化与人口高质量发展研究','Active Ageing and High-quality Population Development'),'China | Major Program, National Social Science Fund of China | PI: Chengbin Liu',z('从社会政策与社会治理角度研究积极老龄化和人口高质量发展的条件。','Studying active ageing and high-quality population development through social-policy and governance perspectives.'),z('调查研究、资料分析与项目协作。','Survey research, evidence analysis and project collaboration.'))}
      ${projectCard(z('突发公共卫生事件中的社会心理问题研究','Social Psychological Problems During Public Health Emergencies in China'),'China | National Social Science Fund of China | PI: Chengbin Liu',z('研究突发公共卫生事件中的风险感知、社会心理反应与治理需求。','Examining risk perception, psychosocial responses and governance needs during public-health emergencies.'),z('调查实施、数据分析与研究写作。','Survey implementation, analysis and research writing.'))}
      ${projectCard(z('新冠疫情社会风险防控研究','Social Risk Prevention and Control During COVID-19'),'China | Central China Think Tank Special Project | PI: Chengbin Liu',z('识别疫情中的社会风险、群体反应与社区治理策略。','Identifying social risks, population responses and community-governance strategies during COVID-19.'),z('研究资料整理、调查与政策分析。','Evidence synthesis, survey work and policy analysis.'))}
      ${projectCard(z('湖南省流动人口动态监测研究','Dynamic Monitoring of the Migrant Population in Hunan Province'),'China | Hunan Health Commission | PI: Shuzhi Hu',z('利用省级监测资料研究流动人口特征、健康与公共服务需求。','Using provincial monitoring data to study migrant-population characteristics, health and public-service needs.'),z('数据整理、分析与项目报告。','Data management, analysis and project reporting.'))}
    </div></section>
    <section class="subsection"><h3 class="subsection-title">${z('当前重点与合作方向','Emerging Priorities & Collaboration')}</h3><div class="credential-strip"><span>ADHD transition</span><span>Dynamic & multimodal risk</span><span>Digital mental-health equity</span><span>Explainable AI</span><span>Human-in-the-loop intervention</span><span>Cross-cultural research</span></div></section>
  `);
  const pub=(title,url,authors,journal,highlight)=>`<article class="publication"><a href="${url}" target="_blank" rel="noopener">${title}</a><p class="authors">${authors}</p><span class="journal">${journal}</span><p class="highlight">${highlight}</p></article>`;
  page('publications',`
    <p class="section-kicker">Publications</p><h2 class="section-title">${z('论文成果','Publications')}</h2><p class="section-lead">${z('按研究方向组织已正式发表或在线发表的成果。点击题目进入期刊或全文页面。','Peer-reviewed outputs organised by research area. Select a title to open the journal or full-text page.')}</p>
    <section class="project-group"><h3>${z('心理健康、逆境与全生命历程发展','Mental Health, Adversity & Life-course Development')}</h3>
      ${pub('How does maternal “belief in a dangerous world” affect maternal and child depressive symptoms during times of crisis?','https://www.sciencedirect.com/science/article/pii/S2666915325000988','Ning Huang, Evelyn Law, H. Chen, Birit F. P. Broekman, J. Huang, S. Cai, A. P. Tan, J. Chan, Yap-Seng Chong, Bobby K. Cheon, Anne Rifkin-Graboi','Journal of Affective Disorders Reports · 2025',z('新加坡纵向队列显示，危机前母亲的危险世界信念与抑郁症状可预测危机期间母亲及儿童的抑郁风险，家庭冲突与疫情压力是重要路径。','A Singapore longitudinal cohort linked pre-crisis maternal dangerous-world beliefs and depression with maternal and child depressive symptoms during crisis, with household conflict and pandemic stress as important pathways.'))}
      ${pub('How does parent–child attachment moderate the relationship between adverse childhood experiences and school bullying in Chinese adolescents: A large cross-sectional study','https://doi.org/10.1037/vio0000616','Ning Huang, Z. Lin, Xiaohan Liu, Fan Yang, Jing Guo','Psychology of Violence · 2025',z('基于20,341名青少年，比较累积童年逆境与多种欺凌受害的关系，并检验亲子依恋能否发挥保护作用。','Among 20,341 adolescents, the study examined cumulative adverse childhood experiences across multiple forms of bullying victimisation and tested the protective role of parent–child attachment.'))}
      ${pub('Does the COVID-19 pandemic increase or decrease the global cyberbullying behaviors? A systematic review and meta-analysis','https://pubmed.ncbi.nlm.nih.gov/37177992/','Ning Huang, Shan Zhang, Yakun Mu, Yebo Yu, Madelon M. E. Riem, Jing Guo','Trauma, Violence, & Abuse · 2024',z('整合36项研究，估计疫情期间网络欺凌的全球发生水平，并区分受害、施暴及与封控和疫情压力相关的风险因素。','Synthesising 36 studies, the review estimated global cyberbullying prevalence during COVID-19 and distinguished victimisation, perpetration and pandemic-related risk factors.'))}
      ${pub('The prevalences, changes, and related factors of child maltreatment during the COVID-19 pandemic: A systematic review','https://pubmed.ncbi.nlm.nih.gov/36549089/','Ning Huang, Fan Yang, Xiaohan Liu, Yashuang Bai, Jing Guo, Madelon M. E. Riem','Child Abuse & Neglect · 2023',z('系统整合35项研究，揭示疫情期间虐待报告可能下降但严重个案增加，并梳理封控及其社会后果带来的风险。','Across 35 studies, the review found that reported maltreatment could decline while severe cases increased, and mapped risks associated with lockdowns and their social consequences.'))}
      ${pub('The moderating effects of colleagueship on the relationship between mental health and perceived stigma among Chinese firefighters','https://pubmed.ncbi.nlm.nih.gov/37079839/','Ning Huang, Yashuang Bai, Fan Yang, Xiaohan Liu, Jing Guo','Psychological Trauma · 2023',z('基于1,328名消防员，显示同事关系能够缓冲心理症状与求助污名之间的关联，提示职业群体干预不能只面向个体。','Among 1,328 firefighters, colleagueship buffered the association between mental-health symptoms and help-seeking stigma, highlighting the importance of workplace context.'))}
      ${pub('Does COVID-19 vaccination affect post-traumatic stress symptoms via risk perception? A large cross-sectional study among the Chinese population','https://pubmed.ncbi.nlm.nih.gov/38052112/','Ning Huang, Xiaohan Liu, Q. Liu, J. Zhang, Y. Fu, Z. Zhu, Jing Guo, X. Li, L. Yang','Public Health · 2024',z('在55,803名参与者中，疫苗接种与较低创伤后应激症状相关，风险感知解释了部分关系，连接了预防行为与心理健康。','Among 55,803 participants, vaccination was associated with lower post-traumatic stress symptoms, with risk perception explaining part of the association between prevention behaviour and mental health.'))}
      ${pub('The synergistic effects of diet and physical activity on sleep quality among Chinese adolescents: A comprehensive cross-sectional study','https://doi.org/10.1017/gmh.2026.10138','Binyang Huang, Ning Huang, Chen Chen, Jing Guo','Cambridge Prisms: Global Mental Health · 2026',z('基于15,059名青少年，从联合暴露而非单一行为出发，识别饮食、活动与睡眠之间兼具协同和反常的交互模式。','Among 15,059 adolescents, the study examined joint rather than isolated behaviours and identified both synergistic and counterintuitive diet–activity patterns in relation to sleep.'))}
    </section>
    <section class="project-group"><h3>${z('多层次健康决定因素与健康公平','Multilevel Determinants of Health & Health Equity')}</h3>
      ${pub('Assessment of Factors Associated With Mental Well-Being Among Chinese Youths at Individual, School, and Province Levels','https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2807377','Peng Zhang, Fan Yang, Ning Huang, Wei Yan, Bo Zhang, Cancan Zhang, Kaiping Peng, Jing Guo','JAMA Network Open · 2023',z('以398,520名中国青少年为样本，同时估计个体、学校与省级因素，展示心理福祉是多层次环境共同塑造的结果。','A national sample of 398,520 Chinese youths estimated individual, school and provincial factors together, showing that well-being is jointly shaped across levels.'))}
      ${pub('Determinants of depressive symptoms at individual, school and province levels: A national survey of 398,520 Chinese children and adolescents','https://doi.org/10.1016/j.puhe.2024.01.015','Peng Zhang, Ning Huang, Fan Yang, Wei Yan, Bing Zhang, Xiaohan Liu, Kaiping Peng, Jing Guo','Public Health · 2024',z('基于全国大样本区分个体、学校和省级抑郁相关因素，呈现学校教育和地区资源与个体特征之间的多层联系。','Using a national sample, the study separated individual, school and provincial correlates of depressive symptoms and demonstrated cross-level links involving education, regional resources and individual characteristics.'))}
      ${pub('The impact of health insurance on healthcare utilization among migrant patients with chronic diseases and the moderating role of health risk perception','https://scholar.google.com/scholar?q=%22The+impact+of+health+insurance+on+healthcare+utilization+among+migrant+patients+with+chronic+diseases%22','Ning Huang, Xiaohan Liu, Jing Guo','Journal of Peking University (Health Sciences) · 2023',z('聚焦流动慢性病患者，分析医保与医疗服务利用的关系以及健康风险感知如何改变这一关系，连接制度保障与个体认知。','Focusing on migrants with chronic conditions, the study linked health insurance to healthcare utilisation and examined how risk perception modifies this institutional–individual relationship.'))}
    </section>
    <section class="project-group"><h3>${z('数字健康、AI与人群干预科学','Digital Health, AI & Population Intervention Science')}</h3>
      ${pub('The effectiveness of digital technology interventions for cognitive function in older adults: a systematic review and meta-analysis of randomized controlled trials','https://pmc.ncbi.nlm.nih.gov/articles/PMC11872853/','Chen Chen, Ning Huang, Ban Hu, Mingyu Zhang, Junliang Yuan, Jing Guo','GeroScience · 2024',z('整合23项随机试验，显示数字技术干预可改善老年人的整体认知及多个认知领域，并识别更有效的实施特征。','Across 23 randomised trials, digital interventions improved global cognition and several cognitive domains while revealing implementation features associated with stronger effects.'))}
    </section>
    <p class="note">${z('完整且持续更新的论文列表请查看 Google Scholar。','For the complete and continuously updated publication record, visit Google Scholar.')}</p><div class="quick"><a href="https://scholar.google.com/citations?user=2YwtiLMAAAAJ&hl=en" target="_blank" rel="noopener">Google Scholar →</a></div>
  `);
  page('insights',`
    <p class="section-kicker">Public Scholarship & Community</p><h2 class="section-title">${z('公共学术传播与社群','Public Scholarship & Community')}</h2><p class="section-lead">${z('面向中外学术社群、学生、健康与教育专业人员及一般公众，把研究证据转化为可理解、可使用的知识与机会。','Serving academic communities in China and internationally, students, health and education professionals, and the public by translating evidence into useful knowledge and opportunities.')}</p>
    <div class="columns"><section class="column"><span class="emoji">🐱</span><h3>喵喵速读</h3><p>${z('前沿健康研究解读，关注设计、关键数字、证据边界与学术表达。','Frontier health-research interpretation, with attention to design, key estimates, evidence boundaries and academic expression.')}</p></section><section class="column"><span class="emoji">🧠</span><h3>喵喵速学</h3><p>${z('科研方法、论文写作与AI增强工作流。','Research methods, academic writing and AI-enhanced workflows.')}</p></section><section class="column wide"><span class="emoji">📡</span><h3>喵喵速递</h3><p>${z('持续更新会议与学术岗位。会议覆盖心理、行为与发展科学主领域及AI交叉方向；岗位分为国内教职、国内外博士后和研究助理。','Continuously updated conferences and academic positions: core psychological, behavioural and developmental science plus AI intersections; domestic faculty, postdoctoral and research-assistant opportunities.')}</p><div class="quick"><a href="?view=conference">${z('全球会议雷达 →','Global conference radar →')}</a><a href="?view=faculty">${z('学术岗位雷达 →','Academic positions radar →')}</a></div></section><section class="column"><span class="emoji">🛠️</span><h3>喵喵工具</h3><p>${z('经过实际使用的科研工具、AI产品与书籍推荐。','Field-tested research tools, AI products and books.')}</p></section><section class="column"><span class="emoji">📖</span><h3>喵喵日记</h3><p>${z('成长、研究反思与访谈记录。','Growth, research reflections and interviews.')}</p></section></div>
    <section class="subsection"><h3 class="subsection-title">${z('学术网络','Academic Networks')}</h3><div class="network-list"><div class="network"><strong>${z('北京大学社会心理实验室','Peking University Social Psychology Lab')}</strong><span>${z('核心成员','Core Member')}</span></div><div class="network"><strong>International Digital Empowerment & Artificial Intelligence Lab for Health (IDEA Lab)</strong><span>Member · <a href="https://www.researchgate.net/lab/International-Digital-Empowerment-AI-Lab-for-Health-IDEA-Lab-Yibo-Wu" target="_blank" rel="noopener">Lab Profile</a></span></div><div class="network"><strong>Doctoral Association of Development</strong><span>Core Member</span></div><div class="network"><strong>Harvard China Health Club: Academia & Innovation</strong><span>Core Member</span></div></div></section>
  `);
  page('contact',`
    <p class="section-kicker">Contact & Collaboration</p><h2 class="section-title">${z('联系与合作','Contact & Collaboration')}</h2><p class="section-lead">${z('欢迎围绕人群健康、心理与行为科学、儿童与家庭发展、数字健康、可解释AI和跨文化研究开展学术合作。','Open to academic collaboration in population health, psychological and behavioural science, child and family development, digital health, interpretable AI and cross-cultural research.')}</p>
    <div class="contact-grid"><section class="contact-card"><h3>${z('联系 Ning','Contact Ning')}</h3><p><a href="mailto:huangning.pku@gmail.com">huangning.pku@gmail.com</a></p><p><a href="https://scholar.google.com/citations?user=2YwtiLMAAAAJ&hl=en" target="_blank" rel="noopener">Google Scholar</a> · <a href="https://orcid.org/0000-0003-3010-0224" target="_blank" rel="noopener">ORCID</a> · <a href="https://www.linkedin.com/in/ning-huang-747972298" target="_blank" rel="noopener">LinkedIn</a></p><p><a href="https://app.notion.com/p/Ning-Huang-de3b6d99216c4b8c8ecba6f59d5ec9f2?source=copy_link" target="_blank" rel="noopener">Academic Profile</a></p></section><section class="contact-card"><h3>${z('合作方向','Collaboration Interests')}</h3><p>${z('跨机构数据研究、儿童与家庭队列、电子健康记录、数字干预、可解释机器学习、实施与政策转化，以及中外研究团队之间的实质性协作。','Cross-institutional data studies, child and family cohorts, electronic health records, digital interventions, interpretable machine learning, implementation and policy translation, and substantive collaboration between research teams in China and internationally.')}</p></section></div>
  `);
  document.querySelector('.tabs').innerHTML=`<button class="tab active" data-tab="conference" data-zh="会议" data-en="Conferences">会议</button><button class="tab" data-tab="faculty" data-zh="国内教职" data-en="Faculty">国内教职</button><button class="tab" data-tab="postdoc" data-zh="博士后" data-en="Postdocs">博士后</button><button class="tab" data-tab="ra" data-zh="研究助理" data-en="Research Assistants">研究助理</button>`;
})();
